name: Build and Deploy Olopo Points API Dev
trigger:
  branches:
    include:
      - main
      - devops

pool:
  vmImage: 'ubuntu-latest'

variables:
  Image_Name: 'olopoimages/points_api'
  Tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build Docker Image
    steps:
    - script: |
        echo "Installing jq"
        sudo apt-get update && sudo apt-get install -y jq
        sudo  apt install awscli
        aws configure set aws_access_key_id $(AWS_ACCESS_KEY)
        aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
        aws configure set default.region ap-south-1
        aws configure set output json
        rm .env
        aws secretsmanager get-secret-value --secret-id points-dev  --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > .env
      displayName: Install jq and awscli
      
    - script: |
        echo "Building Docker image: $(Image_Name):$(Tag)"

        docker build -t $(Image_Name):$(Tag) -f ./Dockerfile . > /dev/null 2>&1

        echo "Logging in to Docker Hub"
        echo $(DOCKERHUB_PASSWORD) | docker login -u $(DOCKERHUB_USERNAME) --password-stdin

        echo "Pushing Docker image to Docker Hub"
        docker push $(Image_Name):$(Tag) > /dev/null 2>&1
        echo "Docker images pushed successfully"
      displayName: 'Publishing The Latest Image'
      env:
        DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)
        DOCKERHUB_PASSWORD: $(DOCKERHUB_PASSWORD)


- stage: Deploy
  displayName: Deploy the Latest Build
  jobs:
  - job: Deploy
    displayName: Deploying Olopo Points System API
    steps:
      - task: SSH@0
        inputs:
          sshEndpoint: 'business-network-dev-server'
          runOptions: 'commands'
          commands: |
            rm /points_system/.env
            echo "IMAGE_TAG=$(Build.BuildId)" > /points_system/.env
            cat /points_system/.env.example >> /points_system/.env
            sh /points_system/script.sh
          readyTimeout: '20000'
